<?php

//Each new term is generated by adding to the previous two terms
//$fibb[i] = $fibb[i-1] + $fibb[i-2]
//for a=0; a 

// highest number to get                                             
$max = 4000000;


// create array of fibonacci numbers
//   we know it starts with 1, 1
$fibonacci = Array(1,1);
// index of next spot in above array
$currentFibonacciIndex = 2;
//$nextFibonacciIndex = 3;
//Then 5;

while ($fibonacci[$currentFibonacciIndex-1] +         
	   $fibonacci[$currentFibonacciIndex-2] < $max) { 

	$fibonacci[$currentFibonacciIndex] = $fibonacci[$currentFibonacciIndex-1] + $fibonacci[$currentFibonacciIndex-2];
	// increment current index
	$currentFibonacciIndex++;
	
}

// print_r($fibonacci);

// holds sum of even fibonacci numbers
$sumOfEven = 0;

foreach ($fibonacci as $number) {
	if ($number % 2 == 0) {
		$sumOfEven += $number;
	}
}
echo $sumOfEven;


?>